---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
library(dplyr)
```


```{r}
books <- read_csv("data/books.csv")
```


```{r}
books
```



```{r}
dim(books)
```


```{r}
is.na(books)
```



```{r}
books
```



```{r}
tidyverse_logo()
```

```{r}
nrow(books)
```



```{r}
ncol(books)
```


```{r}
dim(books)
```



```{r}
names(books)
```


```{r}
head(books, 10)
```


```{r}
tail(books, 100)
```


```{r}
tail(books, 1000)
```

```{r}
glimpse(books)
```


```{r}
view(books)
```


```{r}
books %>% 
  select(title, authors)
```


```{r}
books %>% 
  select(-title)
```


```{r}
books %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```



```{r}
books %>% 
  filter(average_rating == 4.67)
```

```{r}
books %>% 
  filter(language_code != "eng") %>% 
  select(title, average_rating, authors) %>% 
  filter(average_rating <= 4.00) %>% 
  filter(average_rating >= 3.00)

```


```{r}
books %>% 
  filter(language_code != "eng") %>% 
  select(title, average_rating, authors) %>% 
  filter(average_rating <= 4.00 | average_rating >= 3.00)
```

```{r}
rated4.8 <-
filter(books, average_rating > 4.80)
```

```{r}
rated4.7 <-
filter(books, average_rating > 4.70)
```

```{r}
rated4.7
```




```{r}
rated4.7 %>% 
  select(authors, average_rating, ratings_count) %>% 
  filter(ratings_count >= 100)
```



```{r}
books
```




```{r}
books %>% 
  arrange(title)
```

```{r}
books %>% 
  arrange(bookID)
```


```{r}
arrange(books, desc(average_rating)) %>% 
  select(authors, average_rating, num_pages) %>% 
  filter(num_pages >=50) %>% 
  filter(average_rating >=4.6)
```

```{r}
books
```



```{r}
avg_publisher_rating <-
books %>% 
  arrange(publisher)
  mutate(mean(ratings_count))
```


```{r}
books %>% 
  arrange(publisher)

```





```{r}
books %>% 
  mutate(average_rating * 5)
```

```{r}
books %>% 
  mutate(messed_up_page_count = num_pages - 400)
```

#??????????????????????
#yesss!!!

```{r}
books %>% 
  mutate(average_rating_missing = is.na(average_rating)) %>% 
    filter(average_rating_missing == TRUE)


```



```{r}
books %>% 
    filter(ratings_count == is.na(FALSE)) %>% 
  mutate(ratings_count_total = sum(ratings_count))
```




```{r}
books %>%   
  mutate(ratings_count_total = sum(ratings_count, na.rm = TRUE))
```


```{r}
books %>% 
  mutate(mean_average_rating = mean(average_rating, na.rm = TRUE))
```

```{r}
books %>% 
 summarise(mean_average_rating = mean(average_rating, na.rm = TRUE))
```



```{r}
  ratings_pubhouse <- 
  books %>% 
  group_by(publisher)
```



```{r}
books %>% 
  select(publisher)
```


```{r}
ratings_pubhouse
```





```{r}
ratings_pubhouse %>% 
  arrange(publisher)

```



```{r}
summarise(ratings_pubhouse, group_by(ratings_sth = n()))

```

```{r}
publishers_grouped <-
  group_by(books, publisher)
```

```{r}

summarise(publishers_grouped, number_of_books_published = n()) %>%
```


```{r}
publishers_grouped
```




```{r}
hundred_to_three_hundred_pages <- 
  books %>% 
  filter(num_pages >= 100 & num_pages <=300)
```

```{r}
hundred_to_three_hundred_pages
```


```{r}
hundred_to_three_hundred_pages %>% 
  summarise(mean(average_rating))
```



```{r}
four_hundred_to_six_hundred_pages <- 
  books %>% 
  filter(num_pages >= 400 & num_pages <= 600)
```

```{r}
four_hundred_to_six_hundred_pages
```


```{r}
four_hundred_to_six_hundred_pages %>% 
  summarise(mean(average_rating))
```
```{r}
books %>% 
  summarise(mean(average_rating, na.rm = TRUE))
```








```{r}
fifty_most_read_books <-
books %>% 
  arrange(desc(ratings_count)) %>% 
  head(50)
```


```{r}
fifty_most_read_books
```



```{r}
fifty_most_read_books_above_average_rated <-
fifty_most_read_books %>% 
  filter(average_rating > 3.937)
```




```{r}
fifty_most_read_books_below_average_rated <-
fifty_most_read_books %>% 
  filter(average_rating < 3.937) %>% 
  arrange(average_rating)

```



```{r}
fifty_most_read_books_below_average_rated %>% 
  arrange(average_rating)

```



```{r}
fifty_most_read_books_above_average_rated %>% 
  arrange(average_rating)


```


```{r}
fifty_most_read_books_above_average_rated
```



```{r}
sum(is.na(fifty_most_read_books))
```

```{r}
drop_na((books))
```
































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































