---
title: "R Notebook"
output: html_notebook
---

1.

```{r}
library(ggthemes)
library(tidyverse)
library(CodeClanData)
```

```{r}
backpack
```


2.

```{r}
ggplot(backpack) +
  aes(x = backpack_weight) +
  geom_bar()

```

3. 

```{r}
ggplot(backpack) +
  aes(x = backpack_weight, fill = sex) +
  geom_bar(position = "dodge") +
  scale_x_continuous(breaks = 1:35) +
  scale_y_continuous(breaks = 1:10) +
  labs(x = "Backpack Weight",
       y = "Number of People",
       title = "Count of People's Backpack Weights",
       fill = "Sex")
```


4. and 5.

```{r}
ggplot(backpack) +
  aes(x = backpack_weight, y = body_weight, colour = sex) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Backpack Weight",
       y = "Body Weight",
       title = "Body vs Backpack Weights",
       fill = "Sex") +
  scale_x_continuous(breaks = seq(from = 1, to = 35, by = 2)) +
  scale_y_continuous(breaks = seq(from = 0, to = 300, by = 50)) 
  
```


```{r}
backpack <-
backpack %>% 
  mutate(back_problems = as.character(back_problems)) %>% 
  mutate(back_problems = str_replace_all(back_problems, "1", "yes")) %>% 
  mutate(back_problems = str_replace_all(back_problems, "0", "no"))
```


```{r}
ggplot(backpack) +
  aes(x = back_problems, fill = sex) +
  geom_bar(position = "dodge") +
  scale_y_continuous(labels = scales :: percent) +
  ylab("relative frequencies")
```




















































































































































































































































































































































































































































































































































































