---
title: "Lab"
output: html_notebook
---


```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
```

```{r}
ames <-
read_csv("data/ames.csv") %>% 
  clean_names()

ames
```

```{r}
sale_price_stats <- ames %>%
  summarise(
    num = n(),
    mean = mean(sale_price),
    sd = sd(sale_price)
  )
sale_price_stats
  
```


```{r}
ames %>%
  ggplot() +
  geom_histogram(aes(x = sale_price, y = ..density..), col = "black", bins = 25) +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = sale_price_stats$mean, 
      sd = sale_price_stats$sd
    ),
    col = "red"
  ) +
  scale_x_continuous(labels = scales::comma)+
  scale_y_continuous(labels = scales::comma)




```


```{r}
library(infer)

bootstrap_100 <- ames %>% 
  rep_sample_n(size = 100, replace = TRUE, reps = 1000) %>% 
  summarise(mean_sale_price = mean(sale_price))

bootstrap_100
```


```{r}
infer_resample <- ames %>%
  specify(response = sale_price) %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "mean")

infer_ci_95 <- infer_resample %>%
  get_confidence_interval(level = 0.95, type = "percentile")

infer_ci_95
```

#?????????????












































